Document: deer-service
Title: Debian deer-service Manual
Author: <insert document author here>
Abstract: This manual describes what deer-service is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/deer-service/deer-service.sgml.gz

Format: postscript
Files: /usr/share/doc/deer-service/deer-service.ps.gz

Format: text
Files: /usr/share/doc/deer-service/deer-service.text.gz

Format: HTML
Index: /usr/share/doc/deer-service/html/index.html
Files: /usr/share/doc/deer-service/html/*.html
