Document: geolift-service
Title: Debian geolift-service Manual
Author: <insert document author here>
Abstract: This manual describes what geolift-service is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/geolift-service/geolift-service.sgml.gz

Format: postscript
Files: /usr/share/doc/geolift-service/geolift-service.ps.gz

Format: text
Files: /usr/share/doc/geolift-service/geolift-service.text.gz

Format: HTML
Index: /usr/share/doc/geolift-service/html/index.html
Files: /usr/share/doc/geolift-service/html/*.html
